### ISSUE TITLE
ServiceNotShownHelper.java line 55

### ISSUE THREAD

**Issue by felipinbombin** [InspectorIncognito/androidApp#114]
#### in cl.smartcities.isci.transportinspector.database.ServiceNotShownHelper.makeServiceInvisible

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/isci/android/apps/cl.smartcities.isci.transportinspector/issues/57d1a8340aeb16625be9b9d8](https://fabric.io/isci/android/apps/cl.smartcities.isci.transportinspector/issues/57d1a8340aeb16625be9b9d8)

**Comment by felipinbombin** [comment]
@aantoine esto está solucionado en la versión  [v1.4.24](https://github.com/InspectorIncognito/androidApp/releases/tag/v1.4.24) según lo conversado anteriormente, ¿o no?

**Comment by aantoine** [comment]
@felipinbombin asumiendo que lo que lo generó fue lo que te comenté ayer, si, esta solucionado (por ahora xd)
