### ISSUE TITLE
Mapa recalcula posición cada vez que se vuelve a este

### ISSUE THREAD

**Issue by dmunozl** [InspectorIncognito/androidApp#16]
Si se selecciona a un paradero y después se regresa al mapa. La posición de la persona se vuelve a calcular.

**Comment by aantoine** [comment]
Intenté arreglarlo guardando la posición del centro del mapa antes de que cambie de fragment y restaurando esta posición al volver. El problema es que hay un inconsistencia en las funciones de OSMDROID :(, buscaré otra alternativa

**Comment by aantoine** [comment]
Arreglado, era problema de la versión de Osmdroid
