### ISSUE TITLE
SendRequestWithDelay Bug

### ISSUE THREAD

**Issue by aantoine** [InspectorIncognito/androidApp#74]
Error: El callback de SendRequestWithDelay se llama después de haberse cancelado, lo que produce una inconsistencia en el mapa.

Forma de reproducir: 
- Activar el FakeHandler para simular que se va en vehículo
- Seleccionar un paradero (esto lanza la notificación de detección de bus)
- Seleccionar notificación para abrir diálogo de selección de bus
- Cancelar la notificación (click en la 'x')
- Hacer click en el mapa para cerrar el paradero seleccionado

Cuando se cancela la notificación se llama onResume en MapFragment, esto lanza el método para actualizar el paradero seleccionado, hacer click en mapa hace desaparecer el paradero (esperado) pero luego de eso (dependiendo del timing) llega la respuesta de la actualización y se logra un estado inconsistente

Comportamiento esperado: Una vez des-seleccionado el paradero no debería ejecutarse el método del callback de la actualización.

**Comment by felipinbombin** [comment]
Descripción del Error:

-  Se inicia una estrategia (por ejemplo: "En paradero")
-  Consulta información de buses al servidor (handler ya fue ejecutado) y espera
-  [--- Cambia estrategia "A PIE" ---]
-  Servidor responde y actualiza mapa con información de la estrategia que origino la llamada.

Solución: el CallBack asociado a la estrategia que realizó la llamada del servidor verifica si continua siendo el actual en el StrategyContext, si no es así cancela la actualización.

**Comment by aantoine** [comment]
Que ocurre si no cambia la estrategia pero si quien la origina? ie cambio de paradero?

**Comment by felipinbombin** [comment]
Ok. La solución anterior dejaba en memoria un conjunto de objectos innecesariamente. Implementé un refactoring que se resume en lo siguiente:

- La interfaz ServerResponseListener define el método getToken() que devuelve un string para identificar el listener
- La instancia ServerConnection define una variable pública que hace referencia al listener que actuará cuando se reciba una respuesta del servidor
- Cuando sea necesario detener una consulta períodica, el método consultará si el listener de la consulta tiene el token "PERIODIC_REQUEST". Si es así, se reemplaza el listener por un dummy listener.

Commits relacionados:
[177e22f488c5b92d41f9556f35cf0b851ff70ad0](https://github.com/InspectorIncognito/androidApp/commit/177e22f488c5b92d41f9556f35cf0b851ff70ad0)
[db514ea30f04b6fc3193d03ec6145661c98bc1eb](https://github.com/InspectorIncognito/androidApp/commit/db514ea30f04b6fc3193d03ec6145661c98bc1eb)
[51f1cdcc8ac7ac8f8aa77ad9055a0b66d3c96fc1](https://github.com/InspectorIncognito/androidApp/commit/51f1cdcc8ac7ac8f8aa77ad9055a0b66d3c96fc1)
