### ISSUE TITLE
Patente vacía en URL

### ISSUE THREAD

**Issue by aantoine** [InspectorIncognito/androidApp#75]
Cuando el usuario no recuerda la patente o define manualmente un servicio y no ingresa la patente, las consultas realizadas al servidor terminan mal formateadas lo que genera errores

Ej:
-> http://200.9.100.91:8080/android/requestEventsForBus//506
-> http://200.9.100.91:8080/android/requestEventsForBus/506/
-> Bus matching query does not exist.

**Forma de reproducir:**
Subirse a un bus y no especificar la patente, esto genera un mensaje Toast con el texto "Server error"

**Comportamiento esperado:**
No debería generarse un error en la consulta

**Posible solución:**
Al construirse la URL puede agregarse como patente un valor dummy que el servidor reconozca como "patente vacia"

**Comment by aantoine** [comment]
Las request afectadas son las siguientes
- GeBusEventRequest
- GetTokenRequest
- BusEventRequest

**Comment by felipinbombin** [comment]
Agregué una constante que define una patente dummy, un test para verificar que este no pasa el validador, (i.e el usuario no puede ingresarlo) y por último, una verificación que si el usuario no ingresa una patente se use la patente dummy.

commits relacionados:
[commit b8f9519404e073665a5327e6aaa672e9f9321308](https://github.com/InspectorIncognito/androidApp/commit/b8f9519404e073665a5327e6aaa672e9f9321308)
[commit 6a9dfda583cf4e450b207d74282c9eef005a240a](https://github.com/InspectorIncognito/androidApp/commit/6a9dfda583cf4e450b207d74282c9eef005a240a)

**Comment by aantoine** [comment]
Las request ya no generan un problema, @felipinbombin que esta haciendo el servidor por ahora?
Si lo del servidor aun esta incompleto podríamos cerrar esta issue, crear una nueva para el servidor y hacer el link con esta

**Comment by felipinbombin** [comment]
@aantoine  El servidor crea un registro de bus en la base de datos cuando se solicita un token donde una combinación "servicio,patente" no existe. Por el contrario, cuando se solicitan los eventos de un registro de bus que no existe (BusEventRequest), lanza un error. Es el comportamiento esperado por ahora. 

Un futuro issue sería controlar los errores en el servidor pero es más genérico y por lo tanto no se relacionan con este problema. En consecuencia cierro este issue.
