### ISSUE TITLE
Buses con orientación incorrecta

### ISSUE THREAD

**Issue by aantoine** [InspectorIncognito/androidApp#76]
Al consultar por un paradero, todavía aparecen buses que están con la orientación incorrecta.

Ej: 
![screenshot_2016-06-23-12-12-00](https://cloud.githubusercontent.com/assets/4708571/16310792/591e8a52-3944-11e6-94e1-70c4f9341fba.png)

**Forma de reproducir:**
La orientación se define en el servidor, no conozco una forma de reproducir este comportamiento

**Comportamiento esperado:**
La orientación siempre debería apuntar al paradero

**Posible solución:**
NaN

**Comment by felipinbombin** [comment]
Este es un problema de la lógica del servidor. Ver más detalle en el issue /inspectorIncognito/server#25 . Cuando sea resuelto en  el servidor se debe verificar que este comportamiento ya no ocurre en al app y cerrar este issue.

**Comment by felipinbombin** [comment]
resuelto en el servidor. Revisar: InspectorIncognito/server#25
