### ISSUE TITLE
Conulstas de actualización se ejecutan incluso cuando la aplicación esta en pausa

### ISSUE THREAD

**Issue by aantoine** [InspectorIncognito/androidApp#78]
Las requests para actualizar la información de los paraderos y/o buses se ejecuta incluso cuando la actividad sale del foreground

**Forma de reproducir:**

- Seleccionar un paradero
- Llevar la aplicación a en Pausa
- Reanudar la aplicación y velozmente llevarla a en Pausa

En cuanto la app se reanuda se envía una request de actualización, si la respuesta llega **después** de que se haya salido del foreground se obtiene el comportamiento indebido

**Comportamiento esperado:**
Las actualizaciones no se tienen que hacer si la app no esta en foreground

**Posible solución:**
@felipinbombin encontró una

**Comment by felipinbombin** [comment]
**Solución:**
En el instante en que la aplicación es enviada a background, el listener de la última llamada es reemplazado por un listener dummy si contiene el token "PERIODIC_REQUEST". 

Commit relacionado: [938e3ad627b3722a6d9e30d102e9b1c042088a14](https://github.com/InspectorIncognito/androidApp/commit/938e3ad627b3722a6d9e30d102e9b1c042088a14)
